# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/trevormaxjs/Documents/Engineering/Digital_Design/lab8/lab8.srcs/sources_1/ip/data_memory/data_memory.xci
# IP: The module: 'data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevormaxjs/Documents/Engineering/Digital_Design/lab8/lab_5.gen/sources_1/ip/data_memory/data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/trevormaxjs/Documents/Engineering/Digital_Design/lab8/lab8.srcs/sources_1/ip/data_memory/data_memory.xci
# IP: The module: 'data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevormaxjs/Documents/Engineering/Digital_Design/lab8/lab_5.gen/sources_1/ip/data_memory/data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
