# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/trevormaxjs/Documents/Engineering/Digital_Design/lab7/pdatapath_lab7.xdc

# IP: /home/trevormaxjs/Documents/Engineering/Digital_Design/lab7/lab7.srcs/sources_1/ip/data_memory/data_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_memory || ORIG_REF_NAME==data_memory} -quiet] -quiet
